### ISSUE TITLE
Incompatibility with new proj/pyproj versions

### ISSUE THREAD

**Issue by avalentino** [pytroll/pyresample#210]
Recently proj and pyptoj have been update in debian (sid) and we stated having some problem with pyresample.

The problem is reproducible by running the test suite:

```$ python3 setup.py test
Cython will not be used. Use environment variable 'USE_CYTHON=True' to use it
running test
running egg_info
writing pyresample.egg-info/PKG-INFO
writing dependency_links to pyresample.egg-info/dependency_links.txt
writing requirements to pyresample.egg-info/requires.txt
writing top-level names to pyresample.egg-info/top_level.txt
reading manifest file 'pyresample.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'test/test_files/*'
writing manifest file 'pyresample.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/pyresample/ewa/_ll2cr.cpython-37m-x86_64-linux-gnu.so -> pyresample/ewa
copying build/lib.linux-x86_64-3.7/pyresample/ewa/_fornav.cpython-37m-x86_64-linux-gnu.so -> pyresample/ewa
test_area_equal (pyresample.test.test_geometry.Test) ... ok

[...]

test_create_area_def (pyresample.test.test_geometry.TestStackedAreaDefinition)
Test create_area_def and the four sub-methods that call it in AreaDefinition. ... ERROR
test_get_lonlats (pyresample.test.test_geometry.TestStackedAreaDefinition)
Test get_lonlats on StackedAreaDefinition. ... ok

[...]

test_nearest_swath_1d_mask_to_grid_8n (pyresample.test.test_kd_tree.TestXArrayResamplerNN)
Test 1D swath definition to 2D grid definition; 8 neighbors. ... skipped 'Multiple neighbors not supported yet'

[...]

test_area_parser_yaml (pyresample.test.test_utils.TestYAMLAreaParser)
Test YAML area parser. ... ERROR
test_dynamic_area_parser_yaml (pyresample.test.test_utils.TestYAMLAreaParser)
Test YAML area parser on dynamic areas. ... ok

[...]

test_def2yaml_converter (pyresample.test.test_utils.TestMisc) ... ok
test_get_area_def_from_raster (pyresample.test.test_utils.TestMisc) ... proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
ok
test_get_area_def_from_raster_extracts_proj_id (pyresample.test.test_utils.TestMisc) ... proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
ok
test_get_area_def_from_raster_non_georef_respects_proj_dict (pyresample.test.test_utils.TestMisc) ... proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
ok
test_get_area_def_from_raster_non_georef_value_err (pyresample.test.test_utils.TestMisc) ... proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
ok
test_get_area_def_from_raster_rotated_value_err (pyresample.test.test_utils.TestMisc) ... proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
ok
test_proj4_radius_parameters_default (pyresample.test.test_utils.TestMisc) ... ok

[...]

Test Proj creation with EPSG codes ... ok

======================================================================
ERROR: test_create_area_def (pyresample.test.test_geometry.TestStackedAreaDefinition)
Test create_area_def and the four sub-methods that call it in AreaDefinition.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/pyresample/pyresample/test/test_geometry.py", line 1657, in test_create_area_def
    radius=essentials[1], description=description, units=units, rotation=45))
  File "/home/antonio/debian/git/pyresample/pyresample/area_config.py", line 444, in create_area_def
    center = _convert_units(center, 'center', units, p, proj_dict)
  File "/home/antonio/debian/git/pyresample/pyresample/area_config.py", line 577, in _convert_units
    var = _round_poles(var, units, p)
  File "/home/antonio/debian/git/pyresample/pyresample/area_config.py", line 517, in _round_poles
    center = p(*center, inverse=True, errcheck=True)
  File "/home/antonio/debian/git/pyresample/pyresample/_spatial_mp.py", line 157, in __call__
    radians=radians, errcheck=errcheck)
  File "/usr/lib/python3/dist-packages/pyproj/proj.py", line 183, in __call__
    self._inv(inx, iny, errcheck=errcheck)
  File "pyproj/_proj.pyx", line 165, in pyproj._proj.Proj._inv
pyproj.exceptions.ProjError: generic error of unknown origin: (Internal Proj Error: proj_crs_get_sub_crs: Object is not a CompoundCRS)

======================================================================
ERROR: test_area_parser_yaml (pyresample.test.test_utils.TestYAMLAreaParser)
Test YAML area parser.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/pyresample/pyresample/test/test_utils.py", line 96, in test_area_parser_yaml
    'test_latlong')
  File "/home/antonio/debian/git/pyresample/pyresample/area_config.py", line 104, in parse_area_file
    return _parse_yaml_area_file(area_file_name, *regions)
  File "/home/antonio/debian/git/pyresample/pyresample/area_config.py", line 157, in _parse_yaml_area_file
    res.append(create_area_def(**params))
  File "/home/antonio/debian/git/pyresample/pyresample/area_config.py", line 444, in create_area_def
    center = _convert_units(center, 'center', units, p, proj_dict)
  File "/home/antonio/debian/git/pyresample/pyresample/area_config.py", line 577, in _convert_units
    var = _round_poles(var, units, p)
  File "/home/antonio/debian/git/pyresample/pyresample/area_config.py", line 517, in _round_poles
    center = p(*center, inverse=True, errcheck=True)
  File "/home/antonio/debian/git/pyresample/pyresample/_spatial_mp.py", line 157, in __call__
    radians=radians, errcheck=errcheck)
  File "/usr/lib/python3/dist-packages/pyproj/proj.py", line 183, in __call__
    self._inv(inx, iny, errcheck=errcheck)
  File "pyproj/_proj.pyx", line 165, in pyproj._proj.Proj._inv
pyproj.exceptions.ProjError: generic error of unknown origin: (Internal Proj Error: proj_crs_get_sub_crs: Object is not a CompoundCRS)

----------------------------------------------------------------------
Ran 218 tests in 168.949s

FAILED (errors=2, skipped=2)
Test failed: <unittest.runner.TextTestResult run=218 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=218 errors=2 failures=0>
```

The above output has been produced with

* pyresample v1.12.3
* python v3.7
* pyprojv 2.3
* proj v6.1.1

Also I have similar results with the current pyresample master

**Comment by djhoese** [comment]
This is a bug in pyproj 2.3.0 in the way that pyresample uses the `Proj` object and should be fixed in pyproj 2.3.1 which was released just yesterday. The related pyproj bug is https://github.com/pyproj4/pyproj/issues/413.

**Comment by avalentino** [comment]
Thanks @djhoese, I can confirm that updating to pyprroj v2.3.1 also works with my setup.

Regarding messages like

```
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
```

is it something I should worry about?
If not, I think we can close this issue.

Thanks again

**Comment by djhoese** [comment]
Yes and no. My understanding is that in future versions of PROJ (the C library) the `+init=XXXX:YYYY` syntax will no longer be supported and instead `XXXX:YYYY` (ex. `EPSG:4326`) will be the preferred syntax. Pyresample is currently in a transition period for this syntax where, in the master branch, I've tried to switch to the `XXXX:YYYY` syntax where possible but rely on the PROJ library's warnings when users provide it. I think the warnings you're seeing with tests are likely from some remaining usages in pyresample.

So I would say these are known warnings and may be a problem in the future. We are trying to inform users (as is PROJ) that the old syntax should no longer be used. Some of the changes in master were specifically made to remove the dependency pyresample has on `AreaDefinition.proj_dict` where this `XXXX:YYYY` syntax causes problems.

We'll close this for now and can open a new issue if this because something more than a warning for a real world user use case.
