### ISSUE TITLE
Misleading error when area file doesn't exist

### ISSUE THREAD

**Issue by mraspaud** [pytroll/pyresample#250]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
# Your code here
import pyresample.area_config
pyresample.area_config.load_area('file_that_does_not_exist.yaml', 'ease_sh')
```
#### Problem description
The above produces an obscure error when the file to load doesn't exist:
```python-traceback
Traceback (most recent call last):
  File "c:/Users/amsoe/OneDrive/Desktop/python/Untitled-1.py", line 16, in <module>
    area_def = load_area('areas.yaml', 'ease_sh')
  File "C:\Users\amsoe\AppData\Local\Programs\Python\Python38\lib\site-packages\pyresample\area_config.py", line 75, in load_area
    area_list = parse_area_file(area_file_name, *regions)
  File "C:\Users\amsoe\AppData\Local\Programs\Python\Python38\lib\site-packages\pyresample\area_config.py", line 104, in parse_area_file
    return _parse_yaml_area_file(area_file_name, *regions)
  File "C:\Users\amsoe\AppData\Local\Programs\Python\Python38\lib\site-packages\pyresample\area_config.py", line 139, in _parse_yaml_area_file
    area_dict = _read_yaml_area_file_content(area_file_name)
  File "C:\Users\amsoe\AppData\Local\Programs\Python\Python38\lib\site-packages\pyresample\area_config.py", line 123, in _read_yaml_area_file_content
    area_dict = recursive_dict_update(area_dict, tmp_dict)
  File "C:\Users\amsoe\AppData\Local\Programs\Python\Python38\lib\site-packages\pyresample\utils\_init_.py", line 234, in recursive_dict_update
    for k, v in u.items():
AttributeError: 'str' object has no attribute 'items' 
```

#### Expected Output
A nice error that tells me the file I want to load doesn't exist.

**Comment by djhoese** [comment]
A little more info: this code is taking the filename, notices that the file doesn't exist, and assumes that the string provided must be a YAML string. In hindsight this was a dumb way to implement this on my part.

**Comment by gerritholl** [comment]
I just got bitten by this (again).

Is anyone using the functionality to pass a YAML string directly?  Perhaps this behaviour should be deprecated in favour of:

* If passing a string or pathlib.Path object: interpreted as path
* If passing a stream: content read directly from stream

That way, people who have their area definition in a string can still pass it using `io.StringIO`, plus the stream option opens many other alternatives (compressed files, streams read from a socket, etc.).

**Comment by mraspaud** [comment]
The stream idea is good. On top of that, we could have a special `load_area_from_string` if we want to preserve the yaml-string loading functionality. Not that I've seen it used anywhere though. @gerritholl do you feel like making a small PR ?

**Comment by gerritholl** [comment]
I will have a try.
