### ISSUE TITLE
Test failure on debian sid x86_64

### ISSUE THREAD

**Issue by avalentino** [pytroll/pyresample#26]
I'm try to generate a new debian package for pyresample.

```
$ uname -a
Linux mac2 3.19.0-23-generic #24-Ubuntu SMP Tue Jul 7 18:52:55 UTC 2015 x86_64 GNU/Linux
```

When I run the test suite I get 5 errors and some deprecation warning:

```
$ env PYTHONPATH=. python2.7 /usr/bin/nosetests -v -w pyresample/test

test_append_1d (pyresample.test.test_geometry.Test) ... ok
test_append_2d (pyresample.test.test_geometry.Test) ... ok
test_area_equal (pyresample.test.test_geometry.Test) ... ok
test_area_extent_ll (pyresample.test.test_geometry.Test) ... ok
test_base_lat_invalid (pyresample.test.test_geometry.Test) ... ok
test_base_lon_wrapping (pyresample.test.test_geometry.Test) ... ok
test_base_type (pyresample.test.test_geometry.Test) ... ok
test_boundary (pyresample.test.test_geometry.Test) ... ok
test_cartesian (pyresample.test.test_geometry.Test) ... ok
test_concat_1d (pyresample.test.test_geometry.Test) ... ok
test_concat_2d (pyresample.test.test_geometry.Test) ... ok
Test the function get_xy_from_lonlat ... ok
test_grid_filter (pyresample.test.test_geometry.Test) ... ERROR
test_grid_filter2D (pyresample.test.test_geometry.Test) ... ERROR
test_grid_filter_valid (pyresample.test.test_geometry.Test) ... ERROR
test_latlong_area (pyresample.test.test_geometry.Test) ... ERROR
test_lonlat_precomp (pyresample.test.test_geometry.Test) ... ok
test_not_area_equal (pyresample.test.test_geometry.Test) ... ok
test_swath (pyresample.test.test_geometry.Test) ... ok
test_swath_equal (pyresample.test.test_geometry.Test) ... ok
test_swath_equal_area (pyresample.test.test_geometry.Test) ... ok
test_swath_not_equal (pyresample.test.test_geometry.Test) ... ok
test_swath_not_equal_area (pyresample.test.test_geometry.Test) ... ok
test_swath_wrap (pyresample.test.test_geometry.Test) ... ok
test_from_latlon (pyresample.test.test_grid.Test) ... ok
test_generate_linesample (pyresample.test.test_grid.Test) ... ok
test_latlons (pyresample.test.test_grid.Test) ... ok
test_latlons_mp (pyresample.test.test_grid.Test) ... ok
test_linesample (pyresample.test.test_grid.Test) ... ok
test_linesample_multi (pyresample.test.test_grid.Test) ... ok
test_proj4_string (pyresample.test.test_grid.Test) ... ok
test_proj_coords (pyresample.test.test_grid.Test) ... ok
test_resampled_image (pyresample.test.test_grid.Test) ... ok
test_resampled_image_mp (pyresample.test.test_grid.Test) ... ok
test_single_lonlat (pyresample.test.test_grid.Test) ... ok
test_image (pyresample.test.test_image.Test) ... ok
test_image_segments (pyresample.test.test_image.Test) ... /usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
ok
test_masked_image (pyresample.test.test_image.Test) ... ok
test_masked_image_fill (pyresample.test.test_image.Test) ... ok
test_nearest_neighbour (pyresample.test.test_image.Test) ... ok
test_nearest_neighbour_multi (pyresample.test.test_image.Test) ... ok
test_nearest_neighbour_multi_preproc (pyresample.test.test_image.Test) ... ok
test_nearest_resize (pyresample.test.test_image.Test) ... ok
test_nearest_swath (pyresample.test.test_image.Test) ... ok
test_nearest_swath_segments (pyresample.test.test_image.Test) ... /usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
ok
test_return_type (pyresample.test.test_image.Test) ... ok
test_area_con_cartesian_reduce (pyresample.test.test_kd_tree.Test) ... ok
test_area_con_reduce (pyresample.test.test_kd_tree.Test) ... ok
test_cartesian_reduce (pyresample.test.test_kd_tree.Test) ... ok
test_custom (pyresample.test.test_kd_tree.Test) ... ok
test_custom_base (pyresample.test.test_kd_tree.Test) ... ok
test_custom_multi (pyresample.test.test_kd_tree.Test) ... ok
test_custom_multi_from_sample (pyresample.test.test_kd_tree.Test) ... ok
test_custom_uncert (pyresample.test.test_kd_tree.Test) ... ok
test_gauss (pyresample.test.test_kd_tree.Test) ... ok
test_gauss_base (pyresample.test.test_kd_tree.Test) ... ok
test_gauss_fwhm (pyresample.test.test_kd_tree.Test) ... ok
test_gauss_multi (pyresample.test.test_kd_tree.Test) ... ok
test_gauss_multi_mp (pyresample.test.test_kd_tree.Test) ... ok
test_gauss_multi_mp_segments (pyresample.test.test_kd_tree.Test) ... ok
test_gauss_multi_mp_segments_empty (pyresample.test.test_kd_tree.Test) ... ok
test_gauss_multi_uncert (pyresample.test.test_kd_tree.Test) ... ok
test_gauss_sparse (pyresample.test.test_kd_tree.Test) ... ok
test_gauss_uncert (pyresample.test.test_kd_tree.Test) ... ok
test_masked_fill_float (pyresample.test.test_kd_tree.Test) ... ok
test_masked_fill_int (pyresample.test.test_kd_tree.Test) ... ok
test_masked_full (pyresample.test.test_kd_tree.Test) ... ok
test_masked_full_multi (pyresample.test.test_kd_tree.Test) ... ok
test_masked_gauss (pyresample.test.test_kd_tree.Test) ... ok
test_masked_multi_from_sample (pyresample.test.test_kd_tree.Test) ... ok
test_masked_nearest (pyresample.test.test_kd_tree.Test) ... ok
test_masked_nearest_1d (pyresample.test.test_kd_tree.Test) ... ok
test_nearest (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_1d (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_base (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_empty (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_empty_masked (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_empty_multi (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_empty_multi_masked (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_from_sample (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_mp (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_multi (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_multi_unraveled (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_remap (pyresample.test.test_kd_tree.Test) ... ok
test_nearest_segments (pyresample.test.test_kd_tree.Test) ... /usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1746: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = empty((N,)+dimensions, dtype=dtype)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1749: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tmp.shape = (1,)*i + (dim,)+(1,)*(N-i-1)
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:1751: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = zeros(newdim, dtype)
ok
test_reduce (pyresample.test.test_kd_tree.Test) ... ok
test_reduce_boundary (pyresample.test.test_kd_tree.Test) ... ok
test_area_def2basemap (pyresample.test.test_plot.Test) ... ok
test_easeplot (pyresample.test.test_plot.Test) ... /home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py:76: UserWarning: All geometry objects expect longitudes in the [-180:+180[ range. We will now automatically wrap your longitudes into [-180:+180[, and continue. To avoid this warning next time, use routine utils.wrap_longitudes().
  'To avoid this warning next time, use routine utils.wrap_longitudes().')
ok
test_ellps2axis (pyresample.test.test_plot.Test) ... ok
test_orthoplot (pyresample.test.test_plot.Test) ... /home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py:76: UserWarning: All geometry objects expect longitudes in the [-180:+180[ range. We will now automatically wrap your longitudes into [-180:+180[, and continue. To avoid this warning next time, use routine utils.wrap_longitudes().
  'To avoid this warning next time, use routine utils.wrap_longitudes().')
ok
test_plate_carreeplot (pyresample.test.test_plot.Test) ... ERROR
Testing if a point is inside an area. ... /home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py:76: UserWarning: All geometry objects expect longitudes in the [-180:+180[ range. We will now automatically wrap your longitudes into [-180:+180[, and continue. To avoid this warning next time, use routine utils.wrap_longitudes().
  'To avoid this warning next time, use routine utils.wrap_longitudes().')
ok
Test how much two areas overlap. ... ok
Test if two areas overlap. ... /home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py:76: UserWarning: All geometry objects expect longitudes in the [-180:+180[ range. We will now automatically wrap your longitudes into [-180:+180[, and continue. To avoid this warning next time, use routine utils.wrap_longitudes().
  'To avoid this warning next time, use routine utils.wrap_longitudes().')
/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py:76: UserWarning: All geometry objects expect longitudes in the [-180:+180[ range. We will now automatically wrap your longitudes into [-180:+180[, and continue. To avoid this warning next time, use routine utils.wrap_longitudes().
  'To avoid this warning next time, use routine utils.wrap_longitudes().')
ok
Testing the angle value between two arcs. ... ok
Test if two arcs intersect. ... ok
test_self_map (pyresample.test.test_swath.Test) ... /home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py:76: UserWarning: All geometry objects expect longitudes in the [-180:+180[ range. We will now automatically wrap your longitudes into [-180:+180[, and continue. To avoid this warning next time, use routine utils.wrap_longitudes().
  'To avoid this warning next time, use routine utils.wrap_longitudes().')
ok
test_self_map_multi (pyresample.test.test_swath.Test) ... /home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py:76: UserWarning: All geometry objects expect longitudes in the [-180:+180[ range. We will now automatically wrap your longitudes into [-180:+180[, and continue. To avoid this warning next time, use routine utils.wrap_longitudes().
  'To avoid this warning next time, use routine utils.wrap_longitudes().')
ok
test_area_parser (pyresample.test.test_utils.Test) ... ok
test_load_area (pyresample.test.test_utils.Test) ... ok
test_not_found_exception (pyresample.test.test_utils.Test) ... ok
test_wrap_longitudes (pyresample.test.test_utils.Test) ... ok

======================================================================
ERROR: test_grid_filter (pyresample.test.test_geometry.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/test/test_geometry.py", line 444, in test_grid_filter
    (-20037508.34, -10018754.17, 20037508.34, 10018754.17))
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py", line 514, in __init__
    proj = _spatial_mp.Proj(**proj_dict)
  File "/usr/lib/python2.7/dist-packages/pyproj/__init__.py", line 343, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1190)
RuntimeError: major axis or radius = 0 or not given

======================================================================
ERROR: test_grid_filter2D (pyresample.test.test_geometry.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/test/test_geometry.py", line 479, in test_grid_filter2D
    (-20037508.34, -10018754.17, 20037508.34, 10018754.17))
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py", line 514, in __init__
    proj = _spatial_mp.Proj(**proj_dict)
  File "/usr/lib/python2.7/dist-packages/pyproj/__init__.py", line 343, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1190)
RuntimeError: major axis or radius = 0 or not given

======================================================================
ERROR: test_grid_filter_valid (pyresample.test.test_geometry.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/test/test_geometry.py", line 419, in test_grid_filter_valid
    (-20037508.34, -10018754.17, 20037508.34, 10018754.17))
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py", line 514, in __init__
    proj = _spatial_mp.Proj(**proj_dict)
  File "/usr/lib/python2.7/dist-packages/pyproj/__init__.py", line 343, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1190)
RuntimeError: major axis or radius = 0 or not given

======================================================================
ERROR: test_latlong_area (pyresample.test.test_geometry.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/test/test_geometry.py", line 549, in test_latlong_area
    [-180, -90, 180, 90])
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py", line 514, in __init__
    proj = _spatial_mp.Proj(**proj_dict)
  File "/usr/lib/python2.7/dist-packages/pyproj/__init__.py", line 343, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1190)
RuntimeError: major axis or radius = 0 or not given

======================================================================
ERROR: test_plate_carreeplot (pyresample.test.test_plot.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/test/test_plot.py", line 53, in test_plate_carreeplot
    'test_files', 'areas.cfg'), 'pc_world')[0]
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/utils.py", line 109, in parse_area_file
    area_content)
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/utils.py", line 153, in _create_area
    config['AREA_EXTENT'])
  File "/home/antonio/debian/git/build-area/pyresample-1.1.3/pyresample/geometry.py", line 514, in __init__
    proj = _spatial_mp.Proj(**proj_dict)
  File "/usr/lib/python2.7/dist-packages/pyproj/__init__.py", line 343, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1190)
RuntimeError: major axis or radius = 0 or not given

----------------------------------------------------------------------
Ran 103 tests in 65.963s

FAILED (errors=5)
```

**Comment by avalentino** [comment]
This seems to be fixed in pyresample 1.1.6
