### ISSUE TITLE
Unittest fail on big-endian architectures

### ISSUE THREAD

**Issue by avalentino** [pytroll/pyresample#90]
It seems that the test ` test_get_array_hashable` fails on big endian architectures.
You can find all details about the conditions under which the test has been run at [1].

We are trying to include the new pyresample v1.7.1 in debian but this issue is blocking for us.
Can you pleas provide some hint about a possible solution/workaround?

[1] https://buildd.debian.org/status/package.php?p=pyresample

```
======================================================================
FAIL: test_get_array_hashable (pyresample.test.test_geometry.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/pyresample/test/test_geometry.py", line 226, in test_get_array_hashable
    geometry.get_array_hashable(arr))
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 50.0%)
 x: array([ 51,  51,  51,  51,  51,  51, 243,  63, 205, 204, 204, 204, 204,
       204, 244,  63, 102, 102, 102, 102, 102, 102, 246,  63,   0,   0,
         0,   0,   0,   0, 248,  63], dtype=uint8)
 y: array([ 63, 243,  51,  51,  51,  51,  51,  51,  63, 244, 204, 204, 204,
       204, 204, 205,  63, 246, 102, 102, 102, 102, 102, 102,  63, 248,
         0,   0,   0,   0,   0,   0], dtype=uint8)

----------------------------------------------------------------------
Ran 158 tests in 851.688s

FAILED (failures=1)
```

**Comment by avalentino** [comment]
Probably the one proposed in PR #91 could be a reasonable fix.
Can you please give a look to it?
